# Generated by Django 2.2 on 2020-06-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='description',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
