# Generated by Django 2.2 on 2020-06-26 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0002_reviews_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='ave_rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='contractor.Ratings'),
        ),
    ]
