# Generated by Django 3.0.7 on 2020-06-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0004_bids_j'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='average',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=3),
        ),
    ]
