# Generated by Django 3.0.7 on 2020-06-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0004_auto_20200626_0615'),
        ('contractor', '0005_auto_20200626_0111'),
    ]

    operations = [
    ]
