# Generated by Django 2.2.4 on 2020-06-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_jobs_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='fragile',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
