# Generated by Django 3.0.7 on 2020-06-26 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_jobs_fragile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_location', models.CharField(max_length=100)),
                ('end_location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('attributes', models.CharField(max_length=100)),
                ('fragile', models.BooleanField()),
                ('vehicle_type', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_jobs', to='user.Customers')),
            ],
        ),
    ]
